version: "3.8"

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: apricart-demo
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  app:
    depends_on:
      - postgresdb
    image: ahmadmujtaba200210/apricart_demo:demo
    restart: on-failure
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresdb:5432/apricart-demo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123456789
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  db:
